# Generated by Django 5.2.4 on 2025-07-10 20:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('credit_amount', models.PositiveIntegerField()),
                ('price_cents', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=1000)),
                ('preferred_customer', models.BooleanField(default=False)),
                ('balance', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('transaction_type', models.CharField(choices=[('PURCHASE', 'Purchase'), ('SMS_USAGE', 'SMS Usage'), ('VOICE_USAGE', 'Voice Usage')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reference_id', models.UUIDField(default=uuid.uuid4)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='credits.creditpackage')),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credits.practice')),
            ],
        ),
    ]
