# Generated by Django 5.2.4 on 2025-07-11 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeCredit',
            fields=[
                ('practice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='credits.practice')),
                ('balance', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('preferred_customer', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='practice',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='practice',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='practice',
            name='preferred_customer',
        ),
    ]
