# Generated by Django 5.2.4 on 2025-07-11 19:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0002_practicecredit_remove_practice_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditpackage',
            name='credit_per_SMS',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='creditpackage',
            name='credit_per_VC',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='creditpackage',
            name='is_pay_as_you_go',
            field=models.BooleanField(default=False),
        ),
    ]
