# Generated by Django 5.2.4 on 2025-07-12 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0003_creditpackage_credit_per_sms_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditpackage',
            name='is_pay_as_you_go',
        ),
        migrations.AddField(
            model_name='practicecredit',
            name='current_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='credits.creditpackage'),
        ),
        migrations.AddField(
            model_name='practicecredit',
            name='pay_as_you_go_SMS_count',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='practicecredit',
            name='pay_as_you_go_VC_count',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
