# Generated by Django 5.2.4 on 2025-07-12 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0004_remove_creditpackage_is_pay_as_you_go_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicecredit',
            name='is_package_pay_as_you_go',
            field=models.BooleanField(default=False),
        ),
    ]
