# Generated by Django 5.2.4 on 2025-07-12 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0005_practicecredit_is_package_pay_as_you_go'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practicecredit',
            name='is_package_pay_as_you_go',
        ),
        migrations.AddField(
            model_name='creditpackage',
            name='is_package_pay_as_you_go',
            field=models.BooleanField(default=False),
        ),
    ]
