# Generated by Django 5.2.4 on 2025-07-12 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0006_remove_practicecredit_is_package_pay_as_you_go_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditpackage',
            name='is_package_pay_as_you_go',
            field=models.BooleanField(default=True),
        ),
    ]
