# Generated by Django 5.2.4 on 2025-07-12 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0007_alter_creditpackage_is_package_pay_as_you_go'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='credittransaction',
            index=models.Index(fields=['practice', 'transaction_type', 'created_at'], name='credits_cre_practic_3f4955_idx'),
        ),
    ]
